/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => main_default
});
module.exports = __toCommonJS(main_exports);

// src/index.ts
var import_obsidian = require("obsidian");
var ResearchQuest = class extends import_obsidian.Plugin {
  async onload() {
    console.log("loading plugin");
  }
  async onunload() {
    console.log("unloading plugin");
  }
};

// main.ts
var main_default = ResearchQuest;
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsibWFpbi50cyIsICJzcmMvaW5kZXgudHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCBSZXNlYXJjaFF1ZXN0IGZyb20gXCIuL3NyYy9pbmRleC5qc1wiO1xuXG5leHBvcnQgZGVmYXVsdCBSZXNlYXJjaFF1ZXN0O1xuIiwgImltcG9ydCB7IFBsdWdpbiB9IGZyb20gJ29ic2lkaWFuJztcblxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgUmVzZWFyY2hRdWVzdCBleHRlbmRzIFBsdWdpbiB7XG4gIGFzeW5jIG9ubG9hZCgpIHtcbiAgICBjb25zb2xlLmxvZygnbG9hZGluZyBwbHVnaW4nKVxuICB9XG4gIGFzeW5jIG9udW5sb2FkKCkge1xuICAgIGNvbnNvbGUubG9nKCd1bmxvYWRpbmcgcGx1Z2luJylcbiAgfVxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBOzs7QUNBQSxzQkFBdUI7QUFFdkIsSUFBcUIsZ0JBQXJCLGNBQTJDLHVCQUFPO0FBQUEsRUFDaEQsTUFBTSxTQUFTO0FBQ2IsWUFBUSxJQUFJLGdCQUFnQjtBQUFBLEVBQzlCO0FBQUEsRUFDQSxNQUFNLFdBQVc7QUFDZixZQUFRLElBQUksa0JBQWtCO0FBQUEsRUFDaEM7QUFDRjs7O0FEUEEsSUFBTyxlQUFROyIsCiAgIm5hbWVzIjogW10KfQo=
