name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  check-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main
          path: main

      - name: Compare versions
        run: |
          PR_VERSION=$(jq -r '.version' manifest.json)
          MAIN_VERSION=$(jq -r '.version' main/manifest.json)
          
          if [ "$PR_VERSION" = "$MAIN_VERSION" ]; then
            echo "Error: Version in manifest.json has not been updated"
            echo "Main version: $MAIN_VERSION"
            echo "PR version: $PR_VERSION"
            exit 1
          fi
          
          echo "Version has been updated from $MAIN_VERSION to $PR_VERSION"