name: Release Obsidian plugin

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install asdf & tools
        uses: asdf-vm/actions/install@v3

      - name: Build plugin
        run: |
          pnpm install
          pnpm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION=$(jq -r '.version' manifest.json)

          gh release create "$VERSION" \
            --title="$VERSION" \
            --generate-notes \
            main.js manifest.json
